security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        in_memory:
            memory: ~
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        oauth_token:                                   
            pattern: ^/oauth/v2/token
            security: false
        api_login_register:
            pattern: ^/api/(login|register)
            security: false
        api:
            pattern: ^/api                                
            fos_oauth: true                            
            stateless: true                            
            anonymous: false
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_docs:
            pattern: ^/doc
            anonymous: true
        

    access_control:
        - { path: ^/api/(login|register), roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
        